version: "3.7"
services:
    frontend:
        depends_on:
            - backend
        container_name: sisu_raidcal_frontend
        ports:
            - "3001:3001"
        build:
            context: ./frontend
        environment:
            REACT_APP_API_HOST: backend
        volumes:
            - ./frontend:/usr/src/app
    backend:
        depends_on:
            - database
        container_name: sisu_raidcal_backend
        ports:
            - "3000:3000"
        build:
            context: ./backend
        environment: 
            TYPEORM_HOST: database
            FRONTEND_HOST: frontend
        volumes:
            - ./backend:/usr/src/app
    database:
        container_name: sisu_raidcal_database
        image: postgres:11-alpine
        volumes:
            - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
            - database:/var/lib/lib/postgresql/data
        expose:
            - "5432"
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_HOST: database
            POSTGRES_PORT: 5432
            POSTGRES_USER: sisuraidcal
            POSTGRES_PASSWORD: REDACTED_DB_PASSWORD
            POSTGRES_DB: sisu-raidcal
volumes:
    database: