name: Analyze Infrastructure

on:
  push:
    branches: [main]
    paths: [infra/**, ps-rule.yaml, .github/workflows/analyze-infra.yml]
  pull_request:
    branches: [main]
    paths: [infra/**, ps-rule.yaml, .github/workflows/analyze-infra.yml]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analyze:
    name: PSRule for Azure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run PSRule analysis
        uses: microsoft/ps-rule@46451b8f5258c41beb5ae69ed7190ccbba84112c # v2.9.0
        with:
          modules: PSRule.Rules.Azure
          outputFormat: Sarif
          outputPath: reports/ps-rule-results.sarif
          summary: true

      - name: Upload SARIF results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: always()
        with:
          name: PSRule-Sarif
          path: reports/ps-rule-results.sarif
          retention-days: 7
          if-no-files-found: ignore
